#!/bin/bash

commands=(install compile run dev build)

invalidUsage () {
    echo "Valid Usage: ./goweb <command>"
    echo "commands:"
    for command in ${commands[@]}; do
      printf "\t$command\n"
    done
    exit 1
}

if [ -z $1 ]; then
  invalidUsage
fi

if [ $1 == install ]; then
  go install
  go install github.com/a-h/templ/cmd/templ@latest
  go install github.com/air-verse/air@latest
elif [ $1 == compile ]; then
  templ generate
elif [ $1 == run ]; then
  go run .
elif [ $1 == dev ]; then
  templ generate --watch --proxy="http://localhost:3000" --cmd "air"
elif [ $1 == build ]; then
  go build
else
  invalidUsage
fi
